
networks:
  traefik_proxy:
    external: true

services:
  fastapi:
    build:
      context: . # Le répertoire contenant le Dockerfile
    container_name: fastapi_app
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi.rule=Host(`secret.radhamante.xyz`)"
      - "traefik.http.routers.fastapi.entrypoints=websecure"
      - "traefik.http.routers.fastapi.tls=true"
      - "traefik.http.routers.fastapi.tls.certresolver=myresolver"
      - "traefik.http.services.fastapi.loadbalancer.server.port=8081" # Port exposé par FastAPI
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_IP=${POSTGRES_IP}

    volumes:
      - ./app:/app # Montez votre application dans le conteneur
