
networks:
  traefik_proxy:
    external: true

services:
  fastapi:
    build:
      context: . # Le répertoire contenant le Dockerfile
    container_name: fastapi_app
    restart: always
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secret.rule=Host(`secret.radhamante.xyz`)"
      - "traefik.http.routers.secret.entrypoints=websecure"
      - "traefik.http.routers.secret.tls=true"
      - "traefik.http.routers.secret.tls.certresolver=myresolver"
      - "traefik.http.services.secret.loadbalancer.server.port=8081"
      - "traefik.http.routers.secret.middlewares=crowdsec@docker"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.enabled=true"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.crowdseclapikey=kdNHxCWcLn+0enY/z7KrhodlO/eTnDSiq1H82a6X86Q"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_IP=${POSTGRES_IP}

    volumes:
      - ./app:/app # Montez votre application dans le conteneur
      - ./log_config.yaml:/app/log_config.yaml # Montez votre fichier de configuration de journalisation
      - ./logs:/app/logs # Montez votre répertoire de logs