x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},\d{3}) (?P<message>(?s:.*))$$'

networks:
  traefik_proxy:
    external: true

services:
  fastapi:
    build:
      context: .
    container_name: Secret-Manager-API
    restart: always
    ports:
      - 8081:8081
    networks:
      traefik_proxy:
        ipv4_address: 192.168.1.100
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secret-api.rule=Host(`api.secret.radhamante.fr`)"
      - "traefik.http.routers.secret-api.entrypoints=websecure"
      - "traefik.http.routers.secret-api.tls=true"
      - "traefik.http.routers.secret-api.tls.certresolver=myresolver"
      - "traefik.http.services.secret-api.loadbalancer.server.port=8081"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_IP=${POSTGRES_IP}
    logging: *default-logging

    volumes:
      - .:/api
      - ./log_config.yaml:/app/log_config.yaml
      - ./logs:/logs